# Installing Numpy

In [19]:
!pip install numpy

# Import the package

In [20]:
import numpy as np

# Defining an array

In [21]:
arr = np.array([1,2,3])
print(type(arr))

<class 'numpy.ndarray'>


# arange function

In [7]:
arr = np.arange(start = 0 , stop = 10, step = 2)
print(arr)

[0 2 4 6 8]


# Zeros and ones

In [12]:
arr_zeros = np.zeros(shape = 5)
print(arr_zeros)

[0. 0. 0. 0. 0.]


In [13]:
arr_ones = np.ones(shape = 5)
print(arr_ones)

[1. 1. 1. 1. 1.]


# Linspace

In [22]:
arr_linspace = np.linspace(start = 1, stop = 10, num = 4)
print(arr_linspace)

[ 1.  4.  7. 10.]


# Eye

In [18]:
iden_mat = np.eye(N =3, M = 3)
print(iden_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Rand

In [7]:
random_arr = np.random.rand(4)
print(random_arr)

[0.66516319 0.24750522 0.73197582 0.96937952]


In [23]:
random_mat = np.random.rand(3, 4)
print(random_mat)

[[0.65728961 0.96115145 0.78594408 0.17755506]
 [0.65629733 0.23898678 0.26135821 0.92307374]
 [0.17956469 0.30448881 0.80030088 0.54576566]]


# Randn

In [9]:
randn_array = np.random.randn(3)
print(randn_array)

[ 0.14997628 -0.9831127   0.5554273 ]


In [10]:
randn_mat = np.random.randn(3, 3)
print(randn_mat)

[[-1.07623295  0.83678453 -1.96346184]
 [ 0.93488693 -0.18443601 -0.93878057]
 [-0.14167712  1.80161181 -2.01758573]]


# Randint

In [13]:
randint = np.random.randint(50) # a random number exluding 50
print(randint)

27


In [14]:
randint2 =np.random.randint(1, 10) # a random number from 1(Including) to 10(Exluding)
print(randint2)

5


In [15]:
randint_array =np.random.randint(1, 10, 5) #An array of length 5
print(randint_array)

[2 6 6 3 5]


# Shape

In [18]:
print("Shape of the matrics of 3,3 is" ,randn_mat.shape)
print("Shape of an array of size 5 is" ,randint_array.shape)

Shape of the matrics of 3,3 is (3, 3)
Shape of an array of size 5 is (5,)


# Reshape

In [31]:
#To change the shape of an array
array_a = np.arange(15)
print(f'Array at the beginning:\n { array_a} \nand shape of the array: \n{ array_a.shape}')
array_reshaped = array_a.reshape(3,5)
print(f'Array after reshape: \n{ array_reshaped} \nand shape of the array:\n { array_reshaped.shape}')

Array at the beginning:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
and shape of the array: 
(15,)
Array after reshape: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 
and shape of the array:
 (3, 5)
